version: '2'
services:
  nginx:
    image: nginx:mainline-alpine
    ports:
     - "80:80"
    volumes:
     - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
    depends_on:
     - jenkins
     - gogs
    links:
     - jenkins
     - gogs
  jenkins:
    image: jenkins:alpine
    ports:
     - "8080:8080"
     - "50000:50000"
    links:
      - gogs
      - mongo
      - mysql
    privileged: true
  gogs:
    image: gogs/gogs
    ports:
      - "10022:10022"
      - "10080:10080"
      - "3000:3000"
  mysql:
    image: mysql:5.6.24
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=treinamento
      - MYSQL_USER=treinamento
      - MYSQL_PASSWORD=treinamento
      - MYSQL_DATABASE=treinamento
  mongo:
    image: mongo
    ports:
      - "27017:27017"